name: dev_pilot
description: Command-line interface (CLI) for generating a Flutter project
version: 1.0.13
repository: https://github.com/Mobile-Innowise-Group/DevPilot/tree/main

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.19.5 <4.0.0'



dependencies:
  dio: ^5.1.2
  get_it: ^7.6.0
  logger: ^1.3.0
  args: ^2.4.1
  dcli: ^5.0.0
  mason_logger: ^0.2.6
  archive: ^3.3.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1

executables:
  dev_pilot:

